version: '3'
services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: http-skeleton
      POSTGRES_USER: http-skeleton-user
      POSTGRES_PASSWORD: http-skeleton-password
